<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Share_tutos extends \AppBundle\Entity\Share_tutos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'title_stu', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'description_stu', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'content_stu', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'active_stu', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'created_at_stu', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'updated_at_stu', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'TutoFiles', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'TutosUsers', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'TutosCategories', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'TutoView', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'TutoLike');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'title_stu', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'description_stu', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'content_stu', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'active_stu', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'created_at_stu', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'updated_at_stu', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'TutoFiles', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'TutosUsers', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'TutosCategories', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'TutoView', '' . "\0" . 'AppBundle\\Entity\\Share_tutos' . "\0" . 'TutoLike');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Share_tutos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitleStu($titleStu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitleStu', array($titleStu));

        return parent::setTitleStu($titleStu);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitleStu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitleStu', array());

        return parent::getTitleStu();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionStu($descriptionStu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionStu', array($descriptionStu));

        return parent::setDescriptionStu($descriptionStu);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionStu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionStu', array());

        return parent::getDescriptionStu();
    }

    /**
     * {@inheritDoc}
     */
    public function setContentStu($contentStu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentStu', array($contentStu));

        return parent::setContentStu($contentStu);
    }

    /**
     * {@inheritDoc}
     */
    public function getContentStu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentStu', array());

        return parent::getContentStu();
    }

    /**
     * {@inheritDoc}
     */
    public function setActiveStu($activeStu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActiveStu', array($activeStu));

        return parent::setActiveStu($activeStu);
    }

    /**
     * {@inheritDoc}
     */
    public function getActiveStu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiveStu', array());

        return parent::getActiveStu();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAtStu($createdAtStu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAtStu', array($createdAtStu));

        return parent::setCreatedAtStu($createdAtStu);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAtStu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAtStu', array());

        return parent::getCreatedAtStu();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAtStu($updatedAtStu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAtStu', array($updatedAtStu));

        return parent::setUpdatedAtStu($updatedAtStu);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAtStu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAtStu', array());

        return parent::getUpdatedAtStu();
    }

    /**
     * {@inheritDoc}
     */
    public function addTutoFile(\AppBundle\Entity\Share_tutos_files $tutoFiles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTutoFile', array($tutoFiles));

        return parent::addTutoFile($tutoFiles);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTutoFile(\AppBundle\Entity\Share_tutos_files $tutoFiles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTutoFile', array($tutoFiles));

        return parent::removeTutoFile($tutoFiles);
    }

    /**
     * {@inheritDoc}
     */
    public function getTutoFiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTutoFiles', array());

        return parent::getTutoFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function setTutosUsers(\AppBundle\Entity\Share_users $tutosUsers = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTutosUsers', array($tutosUsers));

        return parent::setTutosUsers($tutosUsers);
    }

    /**
     * {@inheritDoc}
     */
    public function getTutosUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTutosUsers', array());

        return parent::getTutosUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function setTutosCategories(\AppBundle\Entity\Share_categories $tutosCategories = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTutosCategories', array($tutosCategories));

        return parent::setTutosCategories($tutosCategories);
    }

    /**
     * {@inheritDoc}
     */
    public function getTutosCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTutosCategories', array());

        return parent::getTutosCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function insertCreatedAtAuto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'insertCreatedAtAuto', array());

        return parent::insertCreatedAtAuto();
    }

    /**
     * {@inheritDoc}
     */
    public function insertUpdateAtAuto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'insertUpdateAtAuto', array());

        return parent::insertUpdateAtAuto();
    }

    /**
     * {@inheritDoc}
     */
    public function updateDateAuto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateDateAuto', array());

        return parent::updateDateAuto();
    }

    /**
     * {@inheritDoc}
     */
    public function addTutoView(\AppBundle\Entity\Share_tutos_view $tutoView)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTutoView', array($tutoView));

        return parent::addTutoView($tutoView);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTutoView(\AppBundle\Entity\Share_tutos_view $tutoView)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTutoView', array($tutoView));

        return parent::removeTutoView($tutoView);
    }

    /**
     * {@inheritDoc}
     */
    public function getTutoView()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTutoView', array());

        return parent::getTutoView();
    }

    /**
     * {@inheritDoc}
     */
    public function addTutoLike(\AppBundle\Entity\Share_tutos_like $tutoLike)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTutoLike', array($tutoLike));

        return parent::addTutoLike($tutoLike);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTutoLike(\AppBundle\Entity\Share_tutos_like $tutoLike)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTutoLike', array($tutoLike));

        return parent::removeTutoLike($tutoLike);
    }

    /**
     * {@inheritDoc}
     */
    public function getTutoLike()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTutoLike', array());

        return parent::getTutoLike();
    }

}
