<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Share_categories extends \AppBundle\Entity\Share_categories implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Share_categories' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Share_categories' . "\0" . 'name_sca', '' . "\0" . 'AppBundle\\Entity\\Share_categories' . "\0" . 'logo_sca', '' . "\0" . 'AppBundle\\Entity\\Share_categories' . "\0" . 'active_sca', '' . "\0" . 'AppBundle\\Entity\\Share_categories' . "\0" . 'created_at_sca', '' . "\0" . 'AppBundle\\Entity\\Share_categories' . "\0" . 'updated_at_sca', '' . "\0" . 'AppBundle\\Entity\\Share_categories' . "\0" . 'CategoriesTutos');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Share_categories' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Share_categories' . "\0" . 'name_sca', '' . "\0" . 'AppBundle\\Entity\\Share_categories' . "\0" . 'logo_sca', '' . "\0" . 'AppBundle\\Entity\\Share_categories' . "\0" . 'active_sca', '' . "\0" . 'AppBundle\\Entity\\Share_categories' . "\0" . 'created_at_sca', '' . "\0" . 'AppBundle\\Entity\\Share_categories' . "\0" . 'updated_at_sca', '' . "\0" . 'AppBundle\\Entity\\Share_categories' . "\0" . 'CategoriesTutos');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Share_categories $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameSca($nameSca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameSca', array($nameSca));

        return parent::setNameSca($nameSca);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameSca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameSca', array());

        return parent::getNameSca();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogoSca($logoSca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogoSca', array($logoSca));

        return parent::setLogoSca($logoSca);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogoSca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogoSca', array());

        return parent::getLogoSca();
    }

    /**
     * {@inheritDoc}
     */
    public function setActiveSca($activeSca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActiveSca', array($activeSca));

        return parent::setActiveSca($activeSca);
    }

    /**
     * {@inheritDoc}
     */
    public function getActiveSca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiveSca', array());

        return parent::getActiveSca();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAtSca($createdAtSca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAtSca', array($createdAtSca));

        return parent::setCreatedAtSca($createdAtSca);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAtSca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAtSca', array());

        return parent::getCreatedAtSca();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAtSca($updatedAtSca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAtSca', array($updatedAtSca));

        return parent::setUpdatedAtSca($updatedAtSca);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAtSca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAtSca', array());

        return parent::getUpdatedAtSca();
    }

    /**
     * {@inheritDoc}
     */
    public function addCategoriesTuto(\AppBundle\Entity\Share_tutos $categoriesTutos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategoriesTuto', array($categoriesTutos));

        return parent::addCategoriesTuto($categoriesTutos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategoriesTuto(\AppBundle\Entity\Share_tutos $categoriesTutos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategoriesTuto', array($categoriesTutos));

        return parent::removeCategoriesTuto($categoriesTutos);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoriesTutos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoriesTutos', array());

        return parent::getCategoriesTutos();
    }

}
