<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Share_users extends \AppBundle\Entity\Share_users implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'username_sha', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'email_sha', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'password_sha', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'active_sha', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'personal_key_sha', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'grade_sha', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'created_at_sha', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'update_at_sha', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'UsersTutos', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'UsersView', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'UsersLike');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'username_sha', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'email_sha', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'password_sha', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'active_sha', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'personal_key_sha', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'grade_sha', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'created_at_sha', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'update_at_sha', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'UsersTutos', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'UsersView', '' . "\0" . 'AppBundle\\Entity\\Share_users' . "\0" . 'UsersLike');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Share_users $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsernameSha($usernameSha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsernameSha', array($usernameSha));

        return parent::setUsernameSha($usernameSha);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsernameSha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsernameSha', array());

        return parent::getUsernameSha();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailSha($emailSha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailSha', array($emailSha));

        return parent::setEmailSha($emailSha);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailSha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailSha', array());

        return parent::getEmailSha();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordSha($passwordSha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordSha', array($passwordSha));

        return parent::setPasswordSha($passwordSha);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordSha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordSha', array());

        return parent::getPasswordSha();
    }

    /**
     * {@inheritDoc}
     */
    public function setActiveSha($activeSha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActiveSha', array($activeSha));

        return parent::setActiveSha($activeSha);
    }

    /**
     * {@inheritDoc}
     */
    public function getActiveSha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiveSha', array());

        return parent::getActiveSha();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonalKeySha($personalKeySha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonalKeySha', array($personalKeySha));

        return parent::setPersonalKeySha($personalKeySha);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonalKeySha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonalKeySha', array());

        return parent::getPersonalKeySha();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAtSha($createdAtSha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAtSha', array($createdAtSha));

        return parent::setCreatedAtSha($createdAtSha);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAtSha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAtSha', array());

        return parent::getCreatedAtSha();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateAtSha($updateAtSha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateAtSha', array($updateAtSha));

        return parent::setUpdateAtSha($updateAtSha);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateAtSha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateAtSha', array());

        return parent::getUpdateAtSha();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsersTuto(\AppBundle\Entity\Share_tutos $usersTutos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsersTuto', array($usersTutos));

        return parent::addUsersTuto($usersTutos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsersTuto(\AppBundle\Entity\Share_tutos $usersTutos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsersTuto', array($usersTutos));

        return parent::removeUsersTuto($usersTutos);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersTutos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersTutos', array());

        return parent::getUsersTutos();
    }

    /**
     * {@inheritDoc}
     */
    public function setGradeSha($gradeSha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGradeSha', array($gradeSha));

        return parent::setGradeSha($gradeSha);
    }

    /**
     * {@inheritDoc}
     */
    public function getGradeSha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGradeSha', array());

        return parent::getGradeSha();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsersView(\AppBundle\Entity\Share_tutos_view $usersView)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsersView', array($usersView));

        return parent::addUsersView($usersView);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsersView(\AppBundle\Entity\Share_tutos_view $usersView)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsersView', array($usersView));

        return parent::removeUsersView($usersView);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersView()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersView', array());

        return parent::getUsersView();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsersLike(\AppBundle\Entity\Share_tutos_like $usersLike)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsersLike', array($usersLike));

        return parent::addUsersLike($usersLike);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsersLike(\AppBundle\Entity\Share_tutos_like $usersLike)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsersLike', array($usersLike));

        return parent::removeUsersLike($usersLike);
    }

    /**
     * {@inheritDoc}
     */
    public function insertCreatedAtAuto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'insertCreatedAtAuto', array());

        return parent::insertCreatedAtAuto();
    }

    /**
     * {@inheritDoc}
     */
    public function insertUpdateAtAuto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'insertUpdateAtAuto', array());

        return parent::insertUpdateAtAuto();
    }

    /**
     * {@inheritDoc}
     */
    public function insertRoleAtAuto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'insertRoleAtAuto', array());

        return parent::insertRoleAtAuto();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersLike()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersLike', array());

        return parent::getUsersLike();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonExpired', array());

        return parent::isAccountNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonLocked', array());

        return parent::isAccountNonLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsNonExpired', array());

        return parent::isCredentialsNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', array());

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', array());

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', array($serialized));

        return parent::unserialize($serialized);
    }

}
