<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Share_tutos_filesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Share_tutos_filesRepository extends EntityRepository
{

}
