<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Share_tutos_viewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Share_tutos_viewRepository extends EntityRepository
{
    public function getMostViewed($allTutorial)
    {
        $all_view_id = [];
        $view_tutorial = [];

        $qb = $this->createQueryBuilder('v');
        $AllTutorialView = $qb->getQuery()->getResult();

        for ($i = 0; $i < count($AllTutorialView); $i++) {
            array_push($all_view_id, $AllTutorialView[$i]->getViewTuto()->getId());
        }
        $count_occurence_view = 0;
        $occurences_view = array_count_values($all_view_id);
        asort($occurences_view, SORT_NUMERIC);
        $view_number = array_reverse($occurences_view, true);
        foreach ($view_number as $key => $name) {
            $occurences_view[$count_occurence_view++] = $key;
            unset($occurences_view[$key]);
        }
        for ($i = 0; $i < count($occurences_view); $i++) {
            if ($i <= 5) {
                for ($j = 0; $j < count($allTutorial); $j++) {
                    if ($allTutorial[$j]->getId() == $occurences_view[$i]) {
                        array_push($view_tutorial, $allTutorial[$j]);
                    }
                }
            }
        }

        return [$view_tutorial,$view_number];
    }
}
