AppBundle\Entity\Share_tutos_files:
    type: entity
    table: t_share_tutos_files_stf
    manyToOne:
      FilesTuto:
        targetEntity: Share_tutos
        inversedBy: TutoFiles
        joinColumn:
          name: tuto_id_stf
          referencedColumnName: id
    repositoryClass: AppBundle\Repository\Share_tutos_filesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks:
        prePersist: [ insertCreatedAtAuto, insertUpdateAtAuto ]
        preUpdate: [ updateDateAuto ]
    fields:
        name_stf:
            type: string
        real_name_stf:
            type: string
        active_stf:
            type: boolean
            option:
              defaults: 1
        created_at_stf:
            type: datetime
        updated_at_stf:
            type: datetime
